/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.siscons.View;

import DAO.SQLConection;
import Model.ConsulteClientes;
import Model.ConsulteFornecedores;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Bianca
 */
public class CadClienteFornecedor extends javax.swing.JFrame {

    String fisica = "n";
    String juridico = "n";
    String contribuinte = "n";
    String isento = "n";
    String noncontribuinte = "n";
    
    MaskFormatter maskCPF, maskCNPJ;
    
    /**
     * Creates new form CadCliente
     */
    public CadClienteFornecedor() {
        try {
            this.maskCPF = new MaskFormatter("###.###.###-##");
            this.maskCNPJ = new MaskFormatter("##.###.###/####-##");
        } catch (ParseException ex) {
            Logger.getLogger(CadClienteFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        setLocationRelativeTo(null);
        ClienteFisico.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CadClienteNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CadClienteEmail = new javax.swing.JTextField();
        CadClienteCEP = new javax.swing.JTextField();
        CadClienteRua = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CadClienteSalvar = new javax.swing.JButton();
        CadClienteBairro = new javax.swing.JTextField();
        CadClienteNumero = new javax.swing.JTextField();
        CadClienteCidade = new javax.swing.JTextField();
        CadClientePais = new javax.swing.JTextField();
        CadClienteTipo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ClienteFisico = new javax.swing.JRadioButton();
        ClienteJuridico = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        CadClienteFantasia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        CadClienteIE = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        CadClienteIBGE = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        CliEstado = new javax.swing.JTextField();
        BuscaCep = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        CadClienteCGC = new javax.swing.JFormattedTextField();
        CadClienteNasc = new javax.swing.JFormattedTextField();
        CadClienteTelefone = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        CadClienteSalvar1 = new javax.swing.JButton();
        CadClienteSalvar2 = new javax.swing.JButton();

        setTitle("Cadastro de Clientes/Fornecedores");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Telefone:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("E-mail:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("CEP:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 40, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Rua:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));
        getContentPane().add(CadClienteNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 330, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("CPF:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 40, -1));
        getContentPane().add(CadClienteEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 286, -1));

        CadClienteCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadClienteCEPActionPerformed(evt);
            }
        });
        getContentPane().add(CadClienteCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 134, -1));

        CadClienteRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadClienteRuaActionPerformed(evt);
            }
        });
        getContentPane().add(CadClienteRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 286, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Bairro:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Nº:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Cidade:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Pais:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        CadClienteSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CadClienteSalvar.setText("EDITAR");
        CadClienteSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadClienteSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(CadClienteSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 87, 33));

        CadClienteBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadClienteBairroActionPerformed(evt);
            }
        });
        getContentPane().add(CadClienteBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 286, -1));

        CadClienteNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadClienteNumeroActionPerformed(evt);
            }
        });
        getContentPane().add(CadClienteNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 142, -1));
        getContentPane().add(CadClienteCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 142, -1));

        CadClientePais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadClientePaisActionPerformed(evt);
            }
        });
        getContentPane().add(CadClientePais, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 286, -1));

        CadClienteTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tipo de Pessoa:");

        ClienteFisico.setText("Física");
        ClienteFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteFisicoActionPerformed(evt);
            }
        });

        ClienteJuridico.setText("Jurídica");
        ClienteJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteJuridicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CadClienteTipoLayout = new javax.swing.GroupLayout(CadClienteTipo);
        CadClienteTipo.setLayout(CadClienteTipoLayout);
        CadClienteTipoLayout.setHorizontalGroup(
            CadClienteTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadClienteTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(CadClienteTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ClienteJuridico)
                    .addComponent(ClienteFisico))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CadClienteTipoLayout.setVerticalGroup(
            CadClienteTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadClienteTipoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(CadClienteTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ClienteFisico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ClienteJuridico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(CadClienteTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Fantasia:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, -1));

        CadClienteFantasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadClienteFantasiaActionPerformed(evt);
            }
        });
        getContentPane().add(CadClienteFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 57, 530, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Estado:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("IE:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));
        getContentPane().add(CadClienteIE, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 141, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("IBGE:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));
        getContentPane().add(CadClienteIBGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 140, -1));
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(CliEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 140, -1));

        BuscaCep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BuscaCep.setForeground(new java.awt.Color(0, 0, 102));
        BuscaCep.setText("BUSCAR");
        BuscaCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaCepActionPerformed(evt);
            }
        });
        getContentPane().add(BuscaCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Nascimento:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        CadClienteCGC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadClienteCGCActionPerformed(evt);
            }
        });
        getContentPane().add(CadClienteCGC, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 91, 286, -1));

        try {
            CadClienteNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(CadClienteNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 142, -1));

        try {
            CadClienteTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(CadClienteTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 286, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Código:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        getContentPane().add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 100, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 102));
        jButton2.setText("PF");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 102));
        jButton3.setText("PJ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, -1, -1));

        CadClienteSalvar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CadClienteSalvar1.setForeground(new java.awt.Color(153, 0, 0));
        CadClienteSalvar1.setText("EXCLUIR");
        CadClienteSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadClienteSalvar1ActionPerformed(evt);
            }
        });
        getContentPane().add(CadClienteSalvar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 87, 33));

        CadClienteSalvar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CadClienteSalvar2.setForeground(new java.awt.Color(0, 102, 0));
        CadClienteSalvar2.setText("SALVAR");
        CadClienteSalvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadClienteSalvar2ActionPerformed(evt);
            }
        });
        getContentPane().add(CadClienteSalvar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 87, 33));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadClienteNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadClienteNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadClienteNumeroActionPerformed

    private void CadClienteFantasiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadClienteFantasiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadClienteFantasiaActionPerformed

    private void CadClienteCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadClienteCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadClienteCEPActionPerformed

    private void CadClienteRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadClienteRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadClienteRuaActionPerformed

    private void CadClienteSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadClienteSalvarActionPerformed

         // editando os dados dos meus clientes e fornecedores
        if (ClienteFisico.isSelected()) { //Se meu Tipo for Pessoa Fisica selecionada irei fazer consulta no meu banco na tabela de pessoa fisica
            try {
                
                String cod, nome, cgc, nasc, cep, rua, bairro, numero, cidade, pais, estado, telefone, ibge, email;
                cod = codigo.getText();
                nome = CadClienteNome.getText();
                cgc = CadClienteCGC.getText();
                nasc = CadClienteNasc.getText();
                cep = CadClienteCEP.getText();
                rua = CadClienteRua.getText();
                numero = CadClienteNumero.getText();
                bairro = CadClienteBairro.getText();
                cidade = CadClienteCidade.getText();
                pais = CadClientePais.getText();
                estado = CliEstado.getText();
                telefone = CadClienteTelefone.getText();
                ibge = CadClienteIBGE.getText();
                email = CadClienteEmail.getText();

                String sql = "UPDATE PESSOAFISICA SET NOME = '"+nome+"' WHERE idpf = '"+cod+"';";
                    SQLConection conection = new SQLConection();
                    conection.SqlExecution(sql);
                    String sql1 = "UPDATE PESSOAFISICA SET CPF = '"+cgc+"' WHERE idpf = '"+cod+"';";
                    conection.SqlExecution(sql1);
                    String sql2 = "UPDATE PESSOAFISICA SET NASCIMENTO = '"+nasc+"' WHERE idpf = '"+cod+"';";
                    conection.SqlExecution(sql2);
                    String sql3 = "UPDATE PESSOAFISICA SET CEP = '"+cep+"' WHERE idpf = '"+cod+"';";
                    conection.SqlExecution(sql3);
                    String sql4 = "UPDATE PESSOAFISICA SET RUA = '"+rua+"' WHERE idpf = '"+cod+"';";
                    conection.SqlExecution(sql4);
                    String sql5 = "UPDATE PESSOAFISICA SET NUMERO = '"+numero+"' WHERE idpf = '"+cod+"';";
                    conection.SqlExecution(sql5);
                    String sql6 = "UPDATE PESSOAFISICA SET BAIRRO = '"+bairro+"' WHERE idpf = '"+cod+"';";
                    conection.SqlExecution(sql6);
                    String sql33 = "UPDATE PESSOAFISICA SET PAIS = '"+pais+"' WHERE idpf = '"+cod+"';";
                    conection.SqlExecution(sql33);
                    String sql7 = "UPDATE PESSOAFISICA SET CIDADE = '"+cidade+"' WHERE idpf = '"+cod+"';";
                    conection.SqlExecution(sql7);
                    String sql8 = "UPDATE PESSOAFISICA SET ESTADO = '"+estado+"' WHERE idpf = '"+cod+"';";
                    conection.SqlExecution(sql8);
                    String sql9 = "UPDATE PESSOAFISICA SET TELEFONE = '"+telefone+"' WHERE idpf = '"+cod+"';";
                    conection.SqlExecution(sql9);
                    String sq20 = "UPDATE PESSOAFISICA SET IBGE = '"+ibge+"' WHERE idpf = '"+cod+"';";
                    conection.SqlExecution(sq20);
                    String sq21 = "UPDATE PESSOAFISICA SET email = '"+email+"' WHERE idpf = '"+cod+"';";
                    conection.SqlExecution(sq21);
                    
                    JOptionPane.showMessageDialog(null, "CLIENTE ALTERADO COM SUCESSO");
                    
                    this.dispose();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao editar o registro da Pessoa Física");
                JOptionPane.showMessageDialog(null, "Contate seu suporte técnico");
            }
        }  
        
        else if (ClienteJuridico.isSelected()) {
           try {
           String cod, razao, fantasia, cnpj, cep, rua, bairro, numero, pais, estado, cidade, ibge, telefone, IE, email;
                cod = codigo.getText();
                razao = CadClienteNome.getText();
                fantasia = CadClienteFantasia.getText();
                cnpj = CadClienteCGC.getText();
                cep = CadClienteCEP.getText();
                rua = CadClienteRua.getText();
                bairro = CadClienteBairro.getText();
                numero = CadClienteNumero.getText();
                pais = CadClientePais.getText();  
                estado = CliEstado.getText();
                cidade = CadClienteCidade.getText();
                ibge = CadClienteIBGE.getText();
                telefone = CadClienteTelefone.getText();
                IE = CadClienteIE.getText();
                email = CadClienteEmail.getText();

                String sql = "UPDATE PESSOAJURIDICA SET razao = '"+razao+"' WHERE idpj = '"+cod+"';";
                SQLConection conection = new SQLConection();
                conection.SqlExecution(sql);
                String sql1 = "UPDATE PESSOAJURIDICA SET fantasia = '"+fantasia+"' WHERE idpj = '"+cod+"';";
                conection.SqlExecution(sql1);
                String sq122 = "UPDATE PESSOAJURIDICA SET CNPJ = '"+cnpj+"' WHERE idpj = '"+cod+"';";
                conection.SqlExecution(sq122);
                String sql3 = "UPDATE PESSOAJURIDICA SET cep = '"+cep+"' WHERE idpj = '"+cod+"';";
                conection.SqlExecution(sql3);
                String sql4 = "UPDATE PESSOAJURIDICA SET RUA = '"+rua+"' WHERE idpj = '"+cod+"';";
                conection.SqlExecution(sql4);
                String sql5 = "UPDATE PESSOAJURIDICA SET NUMERO = '"+numero+"' WHERE idpj = '"+cod+"';";
                conection.SqlExecution(sql5);
                String sql6 = "UPDATE PESSOAJURIDICA SET BAIRRO = '"+bairro+"' WHERE idpj = '"+cod+"';";
                conection.SqlExecution(sql6);
                String sql33 = "UPDATE PESSOAJURIDICA SET PAIS = '"+pais+"' WHERE idpj = '"+cod+"';";
                conection.SqlExecution(sql33);
                String sql7 = "UPDATE PESSOAJURIDICA SET CIDADE = '"+cidade+"' WHERE idpj = '"+cod+"';";
                conection.SqlExecution(sql7);
                String sql8 = "UPDATE PESSOAJURIDICA SET ESTADO = '"+estado+"' WHERE idpj = '"+cod+"';";
                conection.SqlExecution(sql8);
                String sql9 = "UPDATE PESSOAJURIDICA SET TELEFONE = '"+telefone+"' WHERE idpj = '"+cod+"';";
                conection.SqlExecution(sql9);
                String sq20 = "UPDATE PESSOAJURIDICA SET IBGE = '"+ibge+"' WHERE idpj = '"+cod+"';";
                conection.SqlExecution(sq20);
                String sq21 = "UPDATE PESSOAJURIDICA SET email = '"+email+"' WHERE idpj = '"+cod+"';";
                conection.SqlExecution(sq21);
                String sql22 = "UPDATE PESSOAJURIDICA SET IE = '"+IE+"' WHERE idpj = '"+cod+"';"; 
                conection.SqlExecution(sql22);
                JOptionPane.showMessageDialog(null, "FORNECEDOR ALTERADO COM SUCESSO");
                    
                this.dispose();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao editar o registro da Pessoa Juridica");
                JOptionPane.showMessageDialog(null, "Contate seu suporte técnico");
            }
        }
    }//GEN-LAST:event_CadClienteSalvarActionPerformed

    
    private void CadastroPessoaFisica() throws SQLException
    {
/*
  TABELA A SER CRIADA INICIALMENTE PARA VERIFICAR SE ESTÁ SALVADO NO BANCO DE DADOS:
    CREATE TABLE pessoafisica(
        idpf INT PRIMARY KEY AUTO_INCREMENT,
        nome VARCHAR(200) NOT NULL unique,
        cpf varchar(20) not null,
        cep varchar(10),
        rua varchar(100),
        bairro varchar(100),
        numero varchar(8),
        pais varchar(70),
        estado varchar(20),
        cidade varchar(100),
        ibge varchar(8),
        telefone varchar(15),
        email varchar(100),
	nascimento VARCHAR(15)
    );
*/
        
        String nome, cpf, cep, rua, bairro, numero, pais, estado, cidade, ibge, telefone, email, nascimento;
        nome = CadClienteNome.getText();
        cpf = CadClienteCGC.getText();
        cep = CadClienteCEP.getText();
        rua = CadClienteRua.getText();
        numero = CadClienteNumero.getText();
        bairro = CadClienteBairro.getText();
        cidade = CadClienteCidade.getText();
        estado = CliEstado.getText();
        pais = CadClientePais.getText();
        telefone = CadClienteTelefone.getText();
        email = CadClienteEmail.getText();
        ibge = CadClienteIBGE.getText();
        nascimento = CadClienteNasc.getText();
        
        String sql = "INSERT INTO PESSOAFISICA(idpf, nome, cpf, cep, rua, bairro, numero, pais, estado, cidade, ibge, telefone, email, nascimento) VALUES (NULL, '"+nome+"', '"+cpf+"', '"+cep+"', '"+rua+"', '"+bairro+"',  '"+numero+"',  '"+pais+"',  '"+estado+"',  '"+cidade+"',  '"+ibge+"',  '"+telefone+"', '"+email+"',  '"+nascimento+"');";
        SQLConection conection = new SQLConection();
        conection.SqlExecution(sql);
        JOptionPane.showMessageDialog(null, "Pessoa Física Cadastrada");
        this.dispose();
        
    }
    
    private void CadastroPessoaJuridica() throws SQLException
    {
/*
    TABELA A SER CRIADA INICIALMENTE PARA VERIFICAR SE ESTÁ SALVADO NO BANCO DE DADOS:
        CREATE TABLE pessoajuridica(
        idpj INT PRIMARY KEY AUTO_INCREMENT,
        razao VARCHAR(200) NOT NULL unique,
        fantasia varchar(200),
        cnpj varchar(20) not null,
        cep varchar(10),
        rua varchar(100),
        bairro varchar(100),
        numero varchar(10),
        pais varchar(70),
        estado varchar(20),
        cidade varchar(100),
        ibge varchar(10),
        telefone varchar(20),
        IE varchar(20),
        email varchar(100)
    );
*/
        String razao, fantasia, cnpj, cep, rua, bairro, numero, pais, estado, cidade, ibge, telefone, ie, email;
        razao = CadClienteNome.getText();
        fantasia = CadClienteFantasia.getText();
        cnpj = CadClienteCGC.getText();
        cep = CadClienteCEP.getText();
        rua = CadClienteRua.getText();
        numero = CadClienteNumero.getText();
        bairro = CadClienteBairro.getText();
        cidade = CadClienteCidade.getText();
        estado = CliEstado.getText();
        pais = CadClientePais.getText();
        telefone = CadClienteTelefone.getText();
        email = CadClienteEmail.getText();
        ibge = CadClienteIBGE.getText();
        ie = CadClienteIE.getText();
        
        String sql = "INSERT INTO PESSOAJURIDICA(idpj, razao, fantasia, cnpj, cep, rua, bairro, numero, pais, estado, cidade, ibge, telefone, ie, email) VALUES (NULL, '"+razao+"', '"+fantasia+"', '"+cnpj+"', '"+cep+"', '"+rua+"',  '"+bairro+"',  '"+numero+"',  '"+pais+"',  '"+estado+"',  '"+cidade+"',  '"+ibge+"', '"+telefone+"',  '"+ie+"',  '"+email+"');";
        SQLConection conection = new SQLConection();
        conection.SqlExecution(sql);
        JOptionPane.showMessageDialog(null, "Pessoa Jurídica Cadastrada");
        this.dispose();
    }
    
    private void CadClienteBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadClienteBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadClienteBairroActionPerformed

    private void ClienteFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteFisicoActionPerformed
        // ao selecionar pessoa fisica
        if (ClienteFisico.isSelected()) {
            ClienteJuridico.setSelected(false);
            jLabel2.setText("Nome:");
            CadClienteFantasia.setEditable(false);
            jLabel3.setText("CPF:");
            CadClienteIE.setEditable(false);
            CadClienteCGC.setValue(null);
            CadClienteCGC.setFormatterFactory(new DefaultFormatterFactory(maskCPF));
        } 
    }//GEN-LAST:event_ClienteFisicoActionPerformed

    private void ClienteJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteJuridicoActionPerformed
        // ao selecionar pessoa juridica
        if (ClienteJuridico.isSelected()) {
            ClienteFisico.setSelected(false);
            fisica = "n";
            juridico = "s";
            jLabel2.setText("Razão Social:");
            CadClienteFantasia.setEditable(true);
            jLabel3.setText("CNPJ:");
            CadClienteIE.setEditable(true);
            CadClienteCGC.setValue(null);
            CadClienteCGC.setFormatterFactory(new DefaultFormatterFactory(maskCNPJ));
        } 
    }//GEN-LAST:event_ClienteJuridicoActionPerformed

    private void BuscaCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaCepActionPerformed
        // TODO add your handling code here:
        Adress adress = new Adress();
        JsonCepConnection jsonCepConnection = new JsonCepConnection();
        jsonCepConnection.setCep(CadClienteCEP.getText());
        try {
            adress = jsonCepConnection.buscaEnderecoPelo(CadClienteCEP.getText());
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar CEP");
        }
        CadClienteRua.setText(adress.getLogradouro());
        CadClienteBairro.setText(adress.getBairro());
        CadClienteCidade.setText(adress.getLocalidade());
        CliEstado.setText(adress.getUf());
        CadClienteIBGE.setText(adress.getIbge());
    }//GEN-LAST:event_BuscaCepActionPerformed

    private void CadClientePaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadClientePaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadClientePaisActionPerformed

    private void CadClienteCGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadClienteCGCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadClienteCGCActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //trazendo informações dos meus clientes e fornecedores cadastrados.
         if (ClienteFisico.isSelected()) { //Se meu Tipo for Pessoa Fisica selecionada irei fazer consulta no meu banco na tabela de pessoa fisica
            try {
                String cod,name, pfcpf, pfcep, pfrua, pfbairro, pfnumero, pfpais, pfestado, pfcidade, pfibge, pftelefone, pfemail, pfnascimento;
            
            String clientepf = codigo.getText();
            String sql = "SELECT idpf, nome, cpf, cep, rua, bairro, numero, pais, estado, cidade, ibge, telefone, email, nascimento  FROM PESSOAFISICA WHERE IDPF LIKE '"+clientepf+"'";

            Connection con = SQLConection.getConnection();
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery(sql);
            
            rs.next();

            cod = Integer.toString(rs.getInt("idpf"));
            name = rs.getString("nome");
            pfcpf = rs.getString("cpf");
            pfcep = rs.getString("cep");
            pfrua = rs.getString("rua");
            pfbairro = rs.getString("bairro");
            pfnumero = rs.getString("numero");
            pfpais = rs.getString("pais");
            pfestado = rs.getString("estado");
            pfcidade = rs.getString("cidade");
            pfibge = rs.getString("ibge");
            pftelefone = rs.getString("telefone");
            pfemail = rs.getString("email");
            pfnascimento = rs.getString("nascimento");
            
            codigo.setText(cod);
            CadClienteNome.setText(name);
            CadClienteCGC.setText(pfcpf);
            CadClienteNasc.setText(pfnascimento);
            CadClienteCEP.setText(pfcep);
            CadClienteRua.setText(pfrua);
            CadClienteNumero.setText(pfnumero);
            CadClienteBairro.setText(pfbairro);
            CadClienteCidade.setText(pfcidade);
            CadClientePais.setText(pfpais);
            CliEstado.setText(pfestado);
            CadClienteTelefone.setText(pftelefone);
            CadClienteIBGE.setText(pfibge);
            CadClienteEmail.setText(pfemail);
            
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao buscar Pessoa Física");
                 JOptionPane.showMessageDialog(null, "Verifique se o cliente está cadastrado");
            }
        }  
        
        else if (ClienteJuridico.isSelected()) {
           try {
            String cod, razaopj, fantasiapj, cnpjpj, pjcep, pjrua, pjbairro, pjnumero, pjpais, pjestado, pjcidade, pjibge, pjtelefone, pjie, pjemail;
            String clientepf = codigo.getText();
            String sql = "SELECT idpj, razao, fantasia, cnpj, cep, rua, bairro, numero, pais, estado, cidade, ibge, telefone, IE, email  FROM PESSOAJURIDICA WHERE idpj LIKE '"+clientepf+"'";
            Connection con = SQLConection.getConnection();
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery(sql);
            
            rs.next();
        
            cod = Integer.toString(rs.getInt("idpj"));
            razaopj = rs.getString("razao");
            fantasiapj = rs.getString("fantasia");
            cnpjpj = rs.getString("cnpj");
            pjcep = rs.getString("cep");
            pjrua = rs.getString("rua");
            pjbairro = rs.getString("bairro");
            pjnumero = rs.getString("numero");
            pjpais = rs.getString("pais");
            pjestado = rs.getString("estado");
            pjcidade = rs.getString("cidade");
            pjibge = rs.getString("ibge");
            pjtelefone = rs.getString("telefone");
            pjie = rs.getString("IE");
            pjemail = rs.getString("email");
            
            
            codigo.setText(cod);
            CadClienteNome.setText(razaopj);
            CadClienteFantasia.setText(fantasiapj);
            CadClienteCGC.setText(cnpjpj);
            CadClienteIE.setText(pjie);
            CadClienteCEP.setText(pjcep);
            CadClienteRua.setText(pjrua);
            CadClienteNumero.setText(pjnumero);
            CadClienteBairro.setText(pjbairro);
            CadClienteCidade.setText(pjcidade);
            CadClientePais.setText(pjpais);
            CliEstado.setText(pjestado);
            CadClienteTelefone.setText(pjtelefone);
            CadClienteIBGE.setText(pjibge);
            CadClienteEmail.setText(pjemail);
            
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao buscar Pessoa Juridica");
                 JOptionPane.showMessageDialog(null, "Verifique se o fornecedor está cadastrado");
            }
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // consultar meus clientes cadastrados
        new ConsulteClientes().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //consultar meus fornecedores cadstrados
        new ConsulteFornecedores().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CadClienteSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadClienteSalvar1ActionPerformed
        //Excluindo registros dos meus clientes e fornecedores desejados
        String message = "Deseja deletar o registro Selecionado?";
        String title = "Confirmação";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
          if (reply == JOptionPane.YES_OPTION)
          {
            if(ClienteFisico.isSelected()) {
                try {
                    String pessoafis = codigo.getText();
                    String sql = "DELETE FROM PESSOAFISICA WHERE IDPF = "+pessoafis+"";
                    SQLConection conection = new SQLConection();
                    conection.SqlExecution(sql);
                    JOptionPane.showMessageDialog(null, "REGISTRO DELETADO COM SUCESSO!");
                    this.dispose();
                } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao deletar registro!");     
            }
            } else if (ClienteJuridico.isSelected()) {
                 try {
                    String pessoajuri = codigo.getText();
                    String sql = "DELETE FROM PESSOAJURIDICA WHERE IDPJ = "+pessoajuri+"";
                    SQLConection conection = new SQLConection();
                    conection.SqlExecution(sql);
                    JOptionPane.showMessageDialog(null, "REGISTRO DELETADO COM SUCESSO!");
                    this.dispose();
                } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao deletar registro!");     
            }
          }

      }     
        
    }//GEN-LAST:event_CadClienteSalvar1ActionPerformed

    private void CadClienteSalvar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadClienteSalvar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadClienteSalvar2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscaCep;
    private javax.swing.JTextField CadClienteBairro;
    private javax.swing.JTextField CadClienteCEP;
    private javax.swing.JFormattedTextField CadClienteCGC;
    private javax.swing.JTextField CadClienteCidade;
    private javax.swing.JTextField CadClienteEmail;
    private javax.swing.JTextField CadClienteFantasia;
    private javax.swing.JTextField CadClienteIBGE;
    private javax.swing.JTextField CadClienteIE;
    private javax.swing.JFormattedTextField CadClienteNasc;
    private javax.swing.JTextField CadClienteNome;
    private javax.swing.JTextField CadClienteNumero;
    private javax.swing.JTextField CadClientePais;
    private javax.swing.JTextField CadClienteRua;
    private javax.swing.JButton CadClienteSalvar;
    private javax.swing.JButton CadClienteSalvar1;
    private javax.swing.JButton CadClienteSalvar2;
    private javax.swing.JFormattedTextField CadClienteTelefone;
    private javax.swing.JPanel CadClienteTipo;
    private javax.swing.JTextField CliEstado;
    private javax.swing.JRadioButton ClienteFisico;
    private javax.swing.JRadioButton ClienteJuridico;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField codigo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
