/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.siscons.View;

import DAO.SQLConection;
import Model.ConsultaBanco;
import Model.ConsulteClientes;
import Model.ConsulteProdutos;
import Model.ConsulteVendedores;
import Model.Faturamento;
import Model.ListaItens;
import java.awt.List;
import static java.lang.ModuleLayer.empty;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getInt;
import static javax.swing.UIManager.getString;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Bianca
 */
public class Pedidos extends javax.swing.JFrame {

    /**
     * Creates new form Pedidos
     */
    MaskFormatter mfdata; //para inserir a mascara para data no meu jfield;
    public Pedidos() {
        try {
            mfdata = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            System.out.println("Insira uma data válida!");
        } 
        initComponents();
        setLocationRelativeTo(null);
        data_venda.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date(System.currentTimeMillis())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        btn_confirmar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nomecli = new javax.swing.JTextField();
        txt_ruacli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_ncli1 = new javax.swing.JTextField();
        txt_cidadecli = new javax.swing.JTextField();
        txt_nomevend = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtcodcli = new javax.swing.JTextField();
        txt_codvend = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_ncli = new javax.swing.JTextField();
        bairrocli = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        valor_tot = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        desconto = new javax.swing.JTextField();
        txt_tot = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txt_descprod = new javax.swing.JTextField();
        codigo_produto = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        vlr_unitario = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        qtd_vendas = new javax.swing.JTextField();
        botao_add = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txt_prod = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        produto_descricao = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        totalizando = new javax.swing.JTextField();
        btn_soma = new javax.swing.JButton();
        botao_rmv = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txt_estoque = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        data_venda = new javax.swing.JFormattedTextField(mfdata);
        jButton8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_vendas = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        txt_pesquisa = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setTitle("Tela de Pedidos");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_confirmar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_confirmar.setForeground(new java.awt.Color(0, 102, 0));
        btn_confirmar.setText("CONFIRMAR ");
        btn_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 600, 190, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, 190, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("VENDAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 110, 50));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Cliente:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Vendedor:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 106, -1, -1));

        txt_nomecli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomecliActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nomecli, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 7, 396, -1));

        txt_ruacli.setEditable(false);
        jPanel1.add(txt_ruacli, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 36, 346, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Endereço:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 36, -1, -1));

        txt_ncli1.setEditable(false);
        txt_ncli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ncli1ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_ncli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 62, 90, 30));

        txt_cidadecli.setEditable(false);
        jPanel1.add(txt_cidadecli, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 60, 346, -1));
        jPanel1.add(txt_nomevend, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 390, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 90, 800, 10));

        txtcodcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodcliActionPerformed(evt);
            }
        });
        jPanel1.add(txtcodcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 7, 125, -1));
        jPanel1.add(txt_codvend, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 114, -1));

        jButton4.setText("Filtrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 7, -1, -1));

        jButton5.setText("Consultar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 7, -1, -1));

        jButton6.setText("Filtrar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, -1, -1));

        jButton7.setText("Consultar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Bairro:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 36, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Cidade:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 64, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Nº:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 60, -1, -1));

        txt_ncli.setEditable(false);
        jPanel1.add(txt_ncli, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 7, 108, -1));

        bairrocli.setEditable(false);
        bairrocli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairrocliActionPerformed(evt);
            }
        });
        jPanel1.add(bairrocli, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 36, 210, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 802, 160));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 578, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Valor Total (R$): ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 560, 110, 20));

        valor_tot.setEditable(false);
        valor_tot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor_totActionPerformed(evt);
            }
        });
        getContentPane().add(valor_tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, 120, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Valor: (R$)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, -1, -1));

        desconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descontoActionPerformed(evt);
            }
        });
        getContentPane().add(desconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, 130, -1));

        txt_tot.setEditable(false);
        getContentPane().add(txt_tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, 130, -1));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 550, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Codigo Produto:");

        txt_descprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descprodActionPerformed(evt);
            }
        });

        codigo_produto.setEditable(false);
        codigo_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigo_produtoActionPerformed(evt);
            }
        });

        jButton10.setText("Filtrar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Consultar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Quantidade:");

        vlr_unitario.setEditable(false);
        vlr_unitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vlr_unitarioActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Valor Unitário:");

        botao_add.setText("Adicionar Item");
        botao_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_addActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Codigo:");

        txt_prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_prodActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Produto:");

        produto_descricao.setEditable(false);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Soma:");

        totalizando.setEditable(false);

        btn_soma.setText("Somar");
        btn_soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_somaActionPerformed(evt);
            }
        });

        botao_rmv.setText("Excluir");
        botao_rmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_rmvActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Estoque");

        txt_estoque.setEditable(false);
        txt_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_estoqueActionPerformed(evt);
            }
        });

        jButton1.setText("Att");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(txt_prod, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_descprod, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton11)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(34, 34, 34)
                                .addComponent(codigo_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vlr_unitario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(totalizando, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_soma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botao_add)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botao_rmv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(produto_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(qtd_vendas, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addContainerGap(26, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txt_descprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton10)
                        .addComponent(jButton11))
                    .addComponent(txt_prod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigo_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(produto_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(qtd_vendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(vlr_unitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_soma)
                    .addComponent(botao_add)
                    .addComponent(botao_rmv)
                    .addComponent(totalizando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel21)
                    .addComponent(txt_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 800, 130));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Desconto (R$):");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Data da Venda:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        new javax.swing.JFormattedTextField(mfdata);
        data_venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_vendaActionPerformed(evt);
            }
        });
        getContentPane().add(data_venda, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 100, -1));

        jButton8.setText("Gravar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 120, -1));

        tabela_vendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Quantidade", "Valor Unitário", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_vendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_vendasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_vendas);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 790, 110));

        jLabel19.setText("Nº:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));
        getContentPane().add(txt_pesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 100, -1));

        jButton9.setText("Consultar");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nomecliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomecliActionPerformed
        // VAI PUXAR O NOME DO CLIENTE REFERENTE AO CODIGO ESCOLHIDO
    }//GEN-LAST:event_txt_nomecliActionPerformed

    private void txt_ncli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ncli1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ncli1ActionPerformed

    private void btn_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmarActionPerformed
        // Chamar tela de faturamento onde a pessoa vai preencher onde o dinheiro irá cair  
        /*
        tabela a ser criada no banco
        create table vendas(
	idvenda int primary key auto_increment,
	datavenda varchar(11),
	id_cliente int unique,
	nome_cli varchar(200),
	rua varchar(100),
	bairro varchar(100),
	numero varchar(8),
	cidade varchar(100),
	id_vendedor int unique,
	nomevend varchar(100),
	valor_wth_desc float,
	desconto float,
	vlr_total float,

	FOREIGN KEY(id_cliente)
	REFERENCES PESSOAFISICA(idpf),

	FOREIGN KEY(id_vendedor)
	REFERENCES VENDEDORES(idvendedor)

);
        
        
        
        
        
        
        */

        String message = "Deseja confirmar a venda?";
        String title = "Confirmação";
        
        
       
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
          if (reply == JOptionPane.YES_OPTION)
          {
               try {
                
                String clienteid = txtcodcli.getText();
                String data = data_venda.getText();
                String clientenome = txt_nomecli.getText();
                String enderecocli = txt_ruacli.getText();
                String bairro = bairrocli.getText();
                String numero = txt_ncli1.getText();
                String cidade = txt_cidadecli.getText();
                String idvend = txt_codvend.getText();
                String nomevend = txt_nomevend.getText();
                String valor_unit = valor_tot.getText();
                String descontinho = desconto.getText();
                String vlr_total = txt_tot.getText();
                SQLConection conection = new SQLConection();
                String sql = "INSERT INTO VENDAS(idvenda, datavenda, id_cliente, nome_cli, rua, bairro, numero, cidade, id_vendedor, nomevend, valor_wth_desc, desconto, vlr_total) VALUES (NULL, '"+data+"','"+clienteid+"', '"+clientenome+"', '"+enderecocli+"', '"+bairro+"', '"+numero+"', '"+cidade+"', '"+idvend+"', '"+nomevend+"', '"+valor_unit+"', '"+descontinho+"','"+vlr_total+"')";
               
                conection.SqlExecution(sql);
                
                this.dispose();    
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro na execução do SQL");
                JOptionPane.showMessageDialog(null, "NÃO FOI POSSÍVEL ESTABELECER CONEXÃO COM O BANCO DE DADOS");
            }
              
              new Faturamento().setVisible(true);
          }
       
    }//GEN-LAST:event_btn_confirmarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtcodcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodcliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodcliActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
          // chamando minha tela onde irei consultar meus vendedores cadastrados;
          new ConsulteVendedores().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // BUSCANDO O VENDEDOR PELO NOME QUE EU DESEJO
         try {
            String codigo, vendedor; 
            
            String vendedores = txt_codvend.getText();
            String sql = "SELECT idvendedor, nome FROM VENDEDORES WHERE IDVENDEDOR LIKE '"+vendedores+"'";

            Connection con = SQLConection.getConnection();
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery(sql);
            
            rs.next();
            
            codigo = Integer.toString(rs.getInt("idvendedor"));
            vendedor = rs.getString("nome");
           
            txt_codvend.setText(codigo);
            txt_nomevend.setText(vendedor);
        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERRO AO BUSCAR VENDEDOR!");
            JOptionPane.showMessageDialog(null, "Consulte se essa vendedor cadastrado!");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // FILTRANDO PELO NOME DO CLIENTE
       try {
            String codigo, cliente, rua, bairro, cidade, numero; 
            
            String clientes = txtcodcli.getText();
            String sql = "SELECT idpf, nome, rua, bairro, cidade, numero  FROM PESSOAFISICA WHERE IDPF LIKE '"+clientes+"'";

            Connection con = SQLConection.getConnection();
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery(sql);
            
            rs.next();
            
            codigo = Integer.toString(rs.getInt("idpf"));
            cliente = rs.getString("nome");
            rua = rs.getString("rua");
            bairro = rs.getString("bairro");
            cidade = rs.getString("cidade");
            numero = rs.getString("numero");
           
            txtcodcli.setText(codigo);
            txt_nomecli.setText(cliente);
            txt_ruacli.setText(rua);
            bairrocli.setText(bairro);
            txt_cidadecli.setText(cidade);
            txt_ncli1.setText(numero);
        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERRO AO BUSCAR O CLIENTE!");
            JOptionPane.showMessageDialog(null, "Consulte se essa cliente está cadastrado ou se está como PESSOA JURÍDICA!");
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Consultando meus clientes cadastrados
        new ConsulteClientes().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_descprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descprodActionPerformed

    private void codigo_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigo_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigo_produtoActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // 
        try {
            String codigo, produto, quantidade, vlr, est; 
            String codprod = txt_prod.getText();
            String sql = "SELECT codigo, descricao, vlr_venda_vista, qtd_estoque FROM PRODUTOS WHERE CODIGO LIKE '"+codprod+"'";
           
            
            Connection con = SQLConection.getConnection();
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery(sql);
            
            rs.next();
            
            codigo = Integer.toString(rs.getInt("codigo"));
            produto = rs.getString("descricao");
            vlr = Float.toString(rs.getFloat("vlr_venda_vista"));
            est = Integer.toString(rs.getInt("qtd_estoque"));
            txt_descprod.setText(produto);
            codigo_produto.setText(codigo);
            produto_descricao.setText(produto);     
            vlr_unitario.setText(vlr);
            txt_estoque.setText(est);
            

                               
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERRO AO BUSCAR O PRODUTO!");
            JOptionPane.showMessageDialog(null, "Consulte o suporte técnico para mais informações!");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
                 new ConsulteProdutos().setVisible(true);

    }//GEN-LAST:event_jButton11ActionPerformed

    private void txt_prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_prodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_prodActionPerformed

    private void bairrocliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairrocliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bairrocliActionPerformed

    private void botao_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_addActionPerformed
        /*Aqui é onde faremos a nossa venda em relação ao produto, ou seja, onde vamos buscar o nosso produto desejado,
        inserir a quantidade desse produto, fazer a soma da equação valor unitario * quantidade desejada do produto 
        e adicionar o item na tabela, entretanto, precisamos validar o saldo desses produtos tambem.
        Ou seja, caso haja saldo na tabela produto atributo quantidade então poderemos prosseguir com a venda,
        caso não haja, iremos validar a condição de não poder continuar com a ocmpra.
        */ 
           String qitdem = qtd_vendas.getText(); //pegando o valor do meu campo de quantidade a ser vendido do determinado produto
           String saldo = txt_estoque.getText(); //pegando o saldo do meu banco que foi informado para o cliente
           int qtd_vend, qtd_estoq; 
           qtd_vend = Integer.valueOf(qitdem); //transformando minha variavel String qitdem em inteiro e armazando na variavel qtd_vend
           qtd_estoq = Integer.valueOf(saldo); //transformando minha variavel String saldo em inteiro e armazenando na variavel qtd_estoq
            if(botao_add.isEnabled()) {  
                if(qtd_vend <= qtd_estoq) { //está validando se o usuario está inserindo uma quantidade maior do que o saldo existente no produto.
                DefaultTableModel modelo = (DefaultTableModel) tabela_vendas.getModel();          
                modelo.addRow(new Object[]{codigo_produto.getText(),produto_descricao.getText(), qtd_vendas.getText(), vlr_unitario.getText() , totalizando.getText()});   
                /* quando o botao botao_add foi apertado, acrescentar o valor no field e ir somando conforme vou apertando.*/
                /*Agora farei com que diminua o meu estoque apos adicionar na lista e atualizar no meu banco de dados*/
                int subt = qtd_estoq - qtd_vend;
                //Connection con = SQLConection.getConnection();
                SQLConection conection = new SQLConection();
                String sql1 = "UPDATE produtos SET qtd_estoque = " + subt + " WHERE codigo = '" + codigo_produto.getText()+ "'";
                    try {
                        conection.SqlExecution(sql1);
                    } catch (SQLException ex) {
                        Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else {
                    JOptionPane.showMessageDialog(null, "SALDO INSUFICIENTE");
                    JOptionPane.showMessageDialog(null, "Verifique o estoque do seu produto");
                }
            }
           codigo_produto.setText(null);
           produto_descricao.setText(null);
           qtd_vendas.setText(null);
           vlr_unitario.setText(null);
           totalizando.setText(null);
           txt_estoque.setText(null);
           txt_prod.setText(null);
           txt_descprod.setText(null);
            
    }//GEN-LAST:event_botao_addActionPerformed

    private void btn_somaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_somaActionPerformed
        String prod, descitem, qtditem, vlrofitem;
        prod = codigo_produto.getText();
        descitem = produto_descricao.getText();
        qtditem = qtd_vendas.getText();
        vlrofitem = vlr_unitario.getText();
        
        Float soma_itens;
        soma_itens = ((Float.valueOf((qtditem)) * (Float.valueOf(vlrofitem))));
        String somatoria = String.valueOf(soma_itens);
        if(btn_soma.isEnabled()) {
            totalizando.setText(somatoria);
            }
         
    }//GEN-LAST:event_btn_somaActionPerformed

    private void valor_totActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor_totActionPerformed
        //
        
        
    }//GEN-LAST:event_valor_totActionPerformed

    private void botao_rmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_rmvActionPerformed
        // excluir meu item selecionado da tabela

           String qitdem = qtd_vendas.getText(); //pegando o valor do meu campo de quantidade a ser vendido do determinado produto
           String saldo = txt_estoque.getText(); //pegando o saldo do meu banco que foi informado para o cliente
           int qtd_vend, qtd_estoq; 
           qtd_vend = Integer.valueOf(qitdem); //transformando minha variavel String qitdem em inteiro e armazando na variavel qtd_vend
           qtd_estoq = Integer.valueOf(saldo); //transformando minha variavel String saldo em inteiro e armazenando na variavel qtd_estoq
       
            if(botao_rmv.isEnabled()){
                DefaultTableModel modelo = (DefaultTableModel) tabela_vendas.getModel();
                modelo.removeRow(tabela_vendas.getSelectedRow());
                tabela_vendas.setModel(modelo);
                int soma = Integer.valueOf(qtd_vendas.getText()) + Integer.valueOf(txt_estoque.getText());
                SQLConection conection = new SQLConection();
                String sql1 = "UPDATE produtos SET qtd_estoque = " + soma + " WHERE codigo = '" + codigo_produto.getText()+ "'";
                    try {
                                conection.SqlExecution(sql1);
                                JOptionPane.showMessageDialog(null,"item excluido");
                                JOptionPane.showMessageDialog(null, "saldo voltado para o estoque");
                        } catch (SQLException ex) {
                                 Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
                        }
            
            }
           codigo_produto.setText(null);
           produto_descricao.setText(null);
           qtd_vendas.setText(null);
           vlr_unitario.setText(null);
           totalizando.setText(null);
           txt_estoque.setText(null);
           txt_prod.setText(null);
           txt_descprod.setText(null);
    }//GEN-LAST:event_botao_rmvActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //salvando todos os valores da minha coluna de total para mostrar no campo de total no valor unitario
        //fazendo o field do meu desconto ser calculado e abatido no valor total 
        //mostrando o valor total com o desconto
        
 
        //dvalor unitario total sem desconto
        int totvalunit = tabela_vendas.getRowCount();
        double tot = 0;
        for(int i = 0; i<totvalunit; i++){
            double descvalue = Double.valueOf(tabela_vendas.getValueAt(i,4).toString());
            tot += descvalue;
        }
        valor_tot.setText(Double.toString(tot));
        
        
        //soma total com desconto
       int sumtot = tabela_vendas.getRowCount();
       double sumt = 0;
       for(int i=0; i<sumtot; i++) {
        double smt = Double.valueOf(tabela_vendas.getValueAt(i, 4).toString());
        sumt += smt;
    }
       String descontinho;
       descontinho = desconto.getText();
       Float dsct = Float.valueOf(descontinho);
       txt_tot.setText(Double.toString(sumt -dsct));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void descontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descontoActionPerformed

    private void txt_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_estoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_estoqueActionPerformed

    private void tabela_vendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_vendasMouseClicked
        // para quando eu for excluir ele voltar o estoque para o produto certo
                
                String qitdem = qtd_vendas.getText(); //pegando o valor do meu campo de quantidade a ser vendido do determinado produto
                String saldo = txt_estoque.getText(); //pegando o saldo do meu banco que foi informado para o cliente
                int i = tabela_vendas.getSelectedRow();
                TableModel model = tabela_vendas.getModel();
                codigo_produto.setText(model.getValueAt(i, 0).toString());
                produto_descricao.setText(model.getValueAt(i,1).toString());
                qtd_vendas.setText(model.getValueAt(i,2).toString());
                vlr_unitario.setText(model.getValueAt(i, 3).toString());
                totalizando.setText(model.getValueAt(i, 4).toString());
                
    }//GEN-LAST:event_tabela_vendasMouseClicked

    private void vlr_unitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vlr_unitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vlr_unitarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 
        try {
            String est; 
            String sql = "SELECT codigo, descricao, vlr_venda_vista, qtd_estoque FROM PRODUTOS WHERE CODIGO LIKE '"+codigo_produto.getText()+"'";
           

            Connection con = SQLConection.getConnection();
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery(sql);
            
            rs.next();
   
            est = Integer.toString(rs.getInt("qtd_estoque"));
            txt_estoque.setText(est);
                                           
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERRO AO BUSCAR O SALDO DO PRODUTO!");
            JOptionPane.showMessageDialog(null, "Consulte o suporte técnico para mais informações!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void data_vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_vendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data_vendaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairrocli;
    private javax.swing.JButton botao_add;
    private javax.swing.JButton botao_rmv;
    private javax.swing.JButton btn_confirmar;
    private javax.swing.JButton btn_soma;
    private javax.swing.JTextField codigo_produto;
    private javax.swing.JTextField data_venda;
    private javax.swing.JTextField desconto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField produto_descricao;
    private javax.swing.JTextField qtd_vendas;
    private javax.swing.JTable tabela_vendas;
    private javax.swing.JTextField totalizando;
    private javax.swing.JTextField txt_cidadecli;
    private javax.swing.JTextField txt_codvend;
    private javax.swing.JTextField txt_descprod;
    private javax.swing.JTextField txt_estoque;
    private javax.swing.JTextField txt_ncli;
    private javax.swing.JTextField txt_ncli1;
    private javax.swing.JTextField txt_nomecli;
    private javax.swing.JTextField txt_nomevend;
    private javax.swing.JTextField txt_pesquisa;
    private javax.swing.JTextField txt_prod;
    private javax.swing.JTextField txt_ruacli;
    private javax.swing.JTextField txt_tot;
    private javax.swing.JTextField txtcodcli;
    private javax.swing.JTextField valor_tot;
    private javax.swing.JTextField vlr_unitario;
    // End of variables declaration//GEN-END:variables

    private Object getFloat(String soma_itens) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
