/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Model;

import DAO.SQLConection;
import com.mycompany.siscons.View.Adress;
import com.mycompany.siscons.View.JsonCepConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Bianca
 */
public class ConsultaBanco extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaBanco
     */
    public ConsultaBanco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtpesquisa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_bancos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtdescricao = new javax.swing.JTextField();
        txttelefone = new javax.swing.JTextField();
        txtcep = new javax.swing.JTextField();
        txtendereco = new javax.swing.JTextField();
        txtcidade = new javax.swing.JTextField();
        txtestado = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setTitle("Bancos Cadastrados");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Descrição:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 23, -1, -1));

        txtpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(txtpesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 27, 351, -1));

        jButton1.setText("Pesqusiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 27, 103, -1));

        tabela_bancos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Telefone", "CEP", "Endereço", "Cidade", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_bancos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_bancosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_bancos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 68, 711, 135));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Descrição:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 221, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Telefone:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 247, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Endereço:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 221, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Cidade:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 249, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Estado:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 277, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("CEP:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 277, -1, -1));
        getContentPane().add(txtdescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 221, 231, -1));
        getContentPane().add(txttelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 249, 231, -1));
        getContentPane().add(txtcep, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 277, 138, -1));
        getContentPane().add(txtendereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 221, 231, -1));
        getContentPane().add(txtcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 249, 231, -1));
        getContentPane().add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 277, 231, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 0));
        jButton2.setText("EXCLUIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, 41));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 102));
        jButton3.setText("EDITAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, 41));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 102));
        jButton4.setText("BUSCAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 277, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Excluindo o registro selecionado na consulta
        try{
            SQLConection conection = new SQLConection();
            DefaultTableModel model = (DefaultTableModel) tabela_bancos.getModel(); 
            int SelectedRowIndex = tabela_bancos.getSelectedRow();
            String SelectRowIndexCod = tabela_bancos.getModel().getValueAt(SelectedRowIndex, 0).toString();
            String sql = "DELETE FROM BANCOS WHERE CODBANCO = "+SelectRowIndexCod+"";           
            conection.SqlExecution(sql);
            JOptionPane.showMessageDialog(rootPane, "REGISTRO EXCLUIDO COM SUCESSO!");
            model.removeRow(SelectedRowIndex);       
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "ERRO AO EXCLUIR O REGISTRO SELECIONADO!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // PUXANDO TODOS OS MEUS REGISTROS CADASTRADOS
        try{
                Connection con = SQLConection.getConnection();
                String sql = "Select * from bancos";
                PreparedStatement stmt = con.prepareStatement(sql);
                ResultSet rs = stmt.executeQuery();
                DefaultTableModel modelo = (DefaultTableModel) tabela_bancos.getModel();
                modelo.setNumRows(0); /* Vai ter nenhuma linha inicialmente, elas serão adicionadas conforme o bd for encontrando no meu banco de dados*/
                    
                while(rs.next()){   /*Enquanto houver dados ele irá fazer esse comando para pegar todas as minhas informações*/
                    modelo.addRow(new Object[]{rs.getString("codbanco"), rs.getString("descricao"), rs.getString("telefone"), rs.getString("cep"), rs.getString("endereco"), rs.getString("cidade"), rs.getString("estado")});   
                }
                con.close();
            } catch (SQLException ex) {
                    Logger.getLogger(ConsultaBanco.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabela_bancosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_bancosMouseClicked
        // Pegar a linha que foi selecionada
            int i = tabela_bancos.getSelectedRow();
            TableModel model = tabela_bancos.getModel();
            txtdescricao.setText(model.getValueAt(i,1).toString());
            txttelefone.setText(model.getValueAt(i,2).toString());
            txtcep.setText(model.getValueAt(i, 3).toString());
            txtendereco.setText(model.getValueAt(1, 4).toString());
            txtcidade.setText(model.getValueAt(1, 5).toString());
            txtestado.setText(model.getValueAt(1, 6).toString());
           
    }//GEN-LAST:event_tabela_bancosMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //UPDATE NOS REGISTROS CADASTRADOS
        try{
            SQLConection conection = new SQLConection();
            DefaultTableModel model = (DefaultTableModel) tabela_bancos.getModel(); 
            int upd = tabela_bancos.getSelectedRow();
            String updCod = tabela_bancos.getModel().getValueAt(upd, 0).toString();
          //  String update = "UPDATE BANCOS SET DESCRICAO = '"+txtdescricao.getText()+"' where codbanco = " +updCod+"";
             String update = "UPDATE BANCOS SET DESCRICAO = '"+txtdescricao.getText()+"', TELEFONE = '"+txttelefone.getText()+"', CEP = '"+txtcep.getText()+"', ENDERECO = '"+txtendereco.getText()+"', CIDADE = '"+txtcidade.getText()+"', ESTADO = '"+txtestado.getText()+"'  where codbanco = " +updCod+"";
            conection.SqlExecution(update);
            JOptionPane.showMessageDialog(rootPane, "REGISTRO ATUALIZADO COM SUCESSO!");          
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "ERRO AO ATUALIZAR O REGISTRO!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // BUSCANDO CEP 
        Adress adress = new Adress();
        JsonCepConnection jsonCepConnection = new JsonCepConnection();
        jsonCepConnection.setCep(txtcep.getText());
        try {
            adress = jsonCepConnection.buscaEnderecoPelo(txtcep.getText());
        } 
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar CEP");
            JOptionPane.showMessageDialog(rootPane, "Informe o CEP coreto!");
        }
        txtendereco.setText(adress.getLogradouro());
        txtcidade.setText(adress.getLocalidade());
        txtestado.setText(adress.getUf());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesquisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_bancos;
    private javax.swing.JTextField txtcep;
    private javax.swing.JTextField txtcidade;
    private javax.swing.JTextField txtdescricao;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtpesquisa;
    private javax.swing.JTextField txttelefone;
    // End of variables declaration//GEN-END:variables
}
