/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.siscons.View;

/**
 *
 * @author Bianca
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        InfosCad = new javax.swing.JMenu();
        InfosCadClientes = new javax.swing.JMenuItem();
        CadProdutos = new javax.swing.JMenuItem();
        CadOperacoes = new javax.swing.JMenuItem();
        CadUsuario = new javax.swing.JMenuItem();
        InfosCot = new javax.swing.JMenu();
        InfosConfig = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISCONS");

        InfosCad.setText("Cadastro");
        InfosCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfosCadActionPerformed(evt);
            }
        });

        InfosCadClientes.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bianca\\Documents\\NetBeansProjects\\Siscons\\src\\main\\java\\com\\mycompany\\siscons\\View\\imagens\\clientes.png")); // NOI18N
        InfosCadClientes.setText("Cadastro Clientes | Fornecedores");
        InfosCadClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfosCadClientesActionPerformed(evt);
            }
        });
        InfosCad.add(InfosCadClientes);

        CadProdutos.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bianca\\Documents\\NetBeansProjects\\Siscons\\src\\main\\java\\com\\mycompany\\siscons\\View\\imagens\\materiais.png")); // NOI18N
        CadProdutos.setText("Cadastro Produtos");
        InfosCad.add(CadProdutos);

        CadOperacoes.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bianca\\Documents\\NetBeansProjects\\Siscons\\src\\main\\java\\com\\mycompany\\siscons\\View\\imagens\\forma-de-pagamento.png")); // NOI18N
        CadOperacoes.setText("Cadastro Operações");
        CadOperacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadOperacoesActionPerformed(evt);
            }
        });
        InfosCad.add(CadOperacoes);

        CadUsuario.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bianca\\Documents\\NetBeansProjects\\Siscons\\src\\main\\java\\com\\mycompany\\siscons\\View\\imagens\\adicionar-usuario.png")); // NOI18N
        CadUsuario.setText("Cadastro Usuarios");
        CadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadUsuarioActionPerformed(evt);
            }
        });
        InfosCad.add(CadUsuario);

        jMenuBar1.add(InfosCad);

        InfosCot.setText("Cotação");
        jMenuBar1.add(InfosCot);

        InfosConfig.setText("Configurações");
        jMenuBar1.add(InfosConfig);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InfosCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfosCadActionPerformed
        // CHAMANDO MINHA TELA DE CADASTRO DE CLIENTES
        
    }//GEN-LAST:event_InfosCadActionPerformed

    private void InfosCadClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfosCadClientesActionPerformed
        new CadClienteFornecedor().setVisible(true);
    }//GEN-LAST:event_InfosCadClientesActionPerformed

    private void CadOperacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadOperacoesActionPerformed
        // Cadastraremos as formas de pagamento por aqui a qual irá chamar a tela de cadastro de pagamento
        new CadOperacoes().setVisible(true);
    }//GEN-LAST:event_CadOperacoesActionPerformed

    private void CadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadUsuarioActionPerformed
        // Salvaremos nossos usuarios novos aqui
        new CadUsuario().setVisible(true); 
    }//GEN-LAST:event_CadUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadOperacoes;
    private javax.swing.JMenuItem CadProdutos;
    private javax.swing.JMenuItem CadUsuario;
    private javax.swing.JMenu InfosCad;
    private javax.swing.JMenuItem InfosCadClientes;
    private javax.swing.JMenu InfosConfig;
    private javax.swing.JMenu InfosCot;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
