/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.siscons.View;

import DAO.SQLConection;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Bianca
 */
public class CadClienteFornecedor extends javax.swing.JFrame {

    String fisica = "n";
    String juridico = "n";
    String contribuinte = "n";
    String isento = "n";
    String noncontribuinte = "n";
    
    /**
     * Creates new form CadCliente
     */
    public CadClienteFornecedor() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CadClienteNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CadClienteCGC = new javax.swing.JTextField();
        CadClienteTelefone = new javax.swing.JTextField();
        CadClienteEmail = new javax.swing.JTextField();
        CadClienteCEP = new javax.swing.JTextField();
        CadClienteRua = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CadClienteSalvar = new javax.swing.JButton();
        CadClienteBairro = new javax.swing.JTextField();
        CadClienteNumero = new javax.swing.JTextField();
        CadClienteCidade = new javax.swing.JTextField();
        CadClienetPais = new javax.swing.JTextField();
        CadClienteTipo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ClienteFisico = new javax.swing.JRadioButton();
        ClienteJuridico = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        CadClienteFantasia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        CadClienteIE = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        CadClienteTipoCli = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        CadClienteIBGE = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        CliEstado = new javax.swing.JTextField();
        BuscaCep = new javax.swing.JButton();
<<<<<<< HEAD

        setTitle("Cadastro de Clientes/Fornecedores");
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Razão Social:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Telefone:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("E-mail:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("CEP:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Rua:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("CPF/CNPJ:");
=======
        jButton1 = new javax.swing.JButton();

        setTitle("Cadastro de Clientes/Fornecedores");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Razão Social:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 23, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Telefone:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 254, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("E-mail:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 294, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("CEP:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 123, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Rua:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 162, -1, -1));
        getContentPane().add(CadClienteNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 23, 503, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("CPF/CNPJ:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 91, -1, -1));
        getContentPane().add(CadClienteCGC, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 91, 257, -1));
        getContentPane().add(CadClienteTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 254, 230, -1));
        getContentPane().add(CadClienteEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 294, 357, -1));
>>>>>>> 53db73a (alterando telas e conectando ao banco)

        CadClienteCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadClienteCEPActionPerformed(evt);
            }
        });
<<<<<<< HEAD
=======
        getContentPane().add(CadClienteCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 126, 134, -1));
>>>>>>> 53db73a (alterando telas e conectando ao banco)

        CadClienteRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadClienteRuaActionPerformed(evt);
            }
        });
<<<<<<< HEAD

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Bairro:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Nº");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Cidade:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Pais:");
=======
        getContentPane().add(CadClienteRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 162, 286, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Bairro:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 188, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Nº");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 123, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Cidade:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 162, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Pais:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
>>>>>>> 53db73a (alterando telas e conectando ao banco)

        CadClienteSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CadClienteSalvar.setForeground(new java.awt.Color(0, 102, 0));
        CadClienteSalvar.setText("SALVAR");
        CadClienteSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadClienteSalvarActionPerformed(evt);
            }
        });
<<<<<<< HEAD
=======
        getContentPane().add(CadClienteSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 334, 87, 33));
>>>>>>> 53db73a (alterando telas e conectando ao banco)

        CadClienteBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadClienteBairroActionPerformed(evt);
            }
        });
<<<<<<< HEAD
=======
        getContentPane().add(CadClienteBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 192, 286, -1));
>>>>>>> 53db73a (alterando telas e conectando ao banco)

        CadClienteNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadClienteNumeroActionPerformed(evt);
            }
        });
<<<<<<< HEAD
=======
        getContentPane().add(CadClienteNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 123, 142, -1));
        getContentPane().add(CadClienteCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 162, 142, -1));
        getContentPane().add(CadClienetPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 224, 236, -1));
>>>>>>> 53db73a (alterando telas e conectando ao banco)

        CadClienteTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tipo de Pessoa:");

        ClienteFisico.setText("Física");
        ClienteFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteFisicoActionPerformed(evt);
            }
        });

        ClienteJuridico.setText("Jurídica");
        ClienteJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteJuridicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CadClienteTipoLayout = new javax.swing.GroupLayout(CadClienteTipo);
        CadClienteTipo.setLayout(CadClienteTipoLayout);
        CadClienteTipoLayout.setHorizontalGroup(
            CadClienteTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadClienteTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(CadClienteTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ClienteJuridico)
                    .addComponent(ClienteFisico))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        CadClienteTipoLayout.setVerticalGroup(
            CadClienteTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadClienteTipoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(CadClienteTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ClienteFisico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ClienteJuridico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

<<<<<<< HEAD
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Fantasia:");
=======
        getContentPane().add(CadClienteTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 23, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Fantasia:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 57, -1, -1));
>>>>>>> 53db73a (alterando telas e conectando ao banco)

        CadClienteFantasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadClienteFantasiaActionPerformed(evt);
            }
        });
<<<<<<< HEAD

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Estado:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("IE:");
=======
        getContentPane().add(CadClienteFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 57, 503, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Estado:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 192, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("IE:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 254, -1, -1));
        getContentPane().add(CadClienteIE, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 254, 141, -1));
>>>>>>> 53db73a (alterando telas e conectando ao banco)

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Indicador IE:");

        jRadioButton3.setText("Contribuinte ICMS");

        jRadioButton4.setText("Contribuinte Isento");

        jRadioButton5.setText("Não Contribuinte");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

<<<<<<< HEAD
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Característica:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("IBGE:");
=======
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 105, -1, 141));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Característica:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 264, -1, -1));
        getContentPane().add(CadClienteTipoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 264, 140, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("IBGE:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 224, -1, -1));
        getContentPane().add(CadClienteIBGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 224, 140, -1));
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(911, 176, 38, 63));
        getContentPane().add(CliEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 194, 140, -1));
>>>>>>> 53db73a (alterando telas e conectando ao banco)

        BuscaCep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BuscaCep.setForeground(new java.awt.Color(0, 0, 102));
        BuscaCep.setText("BUSCAR");
        BuscaCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaCepActionPerformed(evt);
            }
        });
<<<<<<< HEAD

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel15)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CadClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CadClienteFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CadClienteCGC, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CadClienteCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(BuscaCep)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel11)
                        .addGap(43, 43, 43)
                        .addComponent(CadClienteNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CadClienteRua, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(CadClienteCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CadClienteBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)
                        .addGap(22, 22, 22)
                        .addComponent(CliEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(CadClienetPais, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel19)
                        .addGap(26, 26, 26)
                        .addComponent(CadClienteIBGE, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CadClienteTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(48, 48, 48)
                .addComponent(CadClienteTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLabel16)
                .addGap(45, 45, 45)
                .addComponent(CadClienteIE, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel18)
                .addGap(5, 5, 5)
                .addComponent(CadClienteTipoCli, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(64, 64, 64)
                .addComponent(CadClienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(CadClienteSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel15)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(CadClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(CadClienteFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(CadClienteCGC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CadClienteCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BuscaCep))
                            .addComponent(jLabel11)
                            .addComponent(CadClienteNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CadClienteRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(CadClienteCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CadClienteBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(CliEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CadClienetPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(CadClienteIBGE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(CadClienteTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(CadClienteTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(CadClienteIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(CadClienteTipoCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(CadClienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CadClienteSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
=======
        getContentPane().add(BuscaCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 123, -1, -1));

        jButton1.setText("Cadastrar Tipo Fiscal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, -1, -1));
>>>>>>> 53db73a (alterando telas e conectando ao banco)

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadClienteNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadClienteNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadClienteNumeroActionPerformed

    private void CadClienteFantasiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadClienteFantasiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadClienteFantasiaActionPerformed

    private void CadClienteCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadClienteCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadClienteCEPActionPerformed

    private void CadClienteRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadClienteRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadClienteRuaActionPerformed

    private void CadClienteSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadClienteSalvarActionPerformed
        // salvando\ cadastrando clientes
 /**
  TABELA A SER CRIADA INICIALMENTE PARA VERIFICAR SE ESTÁ SALVADO NO BANCO DE DADOS:
  * 
  * CREATE TABLE clientes(
        idcliente INT PRIMARY KEY AUTO_INCREMENT,
        cgc VARCHAR(30) NOT NULL unique,
        nome varchar(200) not null,
        fantasia varchar(200),
        cep varchar(10),
        rua varchar(100),
        bairro varchar(100),
        numero integer(5),
        pais varchar(70),
        estado char(2),
        cidade varchar(100),
        ibge float(8),
        telefone varchar(15),
        IE varchar(20),
        email varchar(100),
        nascimento date
    );
  */
       
                
          
        
        
    }//GEN-LAST:event_CadClienteSalvarActionPerformed

    private void CadClienteBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadClienteBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadClienteBairroActionPerformed

    private void ClienteFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteFisicoActionPerformed
        // ao selecionar pessoa fisica
        if (ClienteFisico.isSelected()) {
            ClienteJuridico.setEnabled(false);
            fisica = "s";
            juridico = "n";
        } 
    }//GEN-LAST:event_ClienteFisicoActionPerformed

    private void ClienteJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteJuridicoActionPerformed
        // ao selecionar pessoa juridica
        if (ClienteJuridico.isSelected()) {
            ClienteFisico.setEnabled(false);
            fisica = "n";
            juridico = "s";
        
        } 
    }//GEN-LAST:event_ClienteJuridicoActionPerformed

    private void BuscaCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaCepActionPerformed
        // TODO add your handling code here:
        Adress adress = new Adress();
        JsonCepConnection jsonCepConnection = new JsonCepConnection();
        jsonCepConnection.setCep(CadClienteCEP.getText());
        try {
            adress = jsonCepConnection.buscaEnderecoPelo(CadClienteCEP.getText());
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar CEP");
        }
        CadClienteRua.setText(adress.getLogradouro());
        CadClienteBairro.setText(adress.getBairro());
        CadClienteCidade.setText(adress.getLocalidade());
        CliEstado.setText(adress.getUf());
        CadClienteIBGE.setText(adress.getIbge());
    }//GEN-LAST:event_BuscaCepActionPerformed

<<<<<<< HEAD
=======
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        new CadTiposFiscais().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

>>>>>>> 53db73a (alterando telas e conectando ao banco)
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscaCep;
    private javax.swing.JTextField CadClienetPais;
    private javax.swing.JTextField CadClienteBairro;
    private javax.swing.JTextField CadClienteCEP;
    private javax.swing.JTextField CadClienteCGC;
    private javax.swing.JTextField CadClienteCidade;
    private javax.swing.JTextField CadClienteEmail;
    private javax.swing.JTextField CadClienteFantasia;
    private javax.swing.JTextField CadClienteIBGE;
    private javax.swing.JTextField CadClienteIE;
    private javax.swing.JTextField CadClienteNome;
    private javax.swing.JTextField CadClienteNumero;
    private javax.swing.JTextField CadClienteRua;
    private javax.swing.JButton CadClienteSalvar;
    private javax.swing.JTextField CadClienteTelefone;
    private javax.swing.JPanel CadClienteTipo;
    private javax.swing.JTextField CadClienteTipoCli;
    private javax.swing.JTextField CliEstado;
    private javax.swing.JRadioButton ClienteFisico;
    private javax.swing.JRadioButton ClienteJuridico;
    private javax.swing.ButtonGroup buttonGroup1;
<<<<<<< HEAD
=======
    private javax.swing.JButton jButton1;
>>>>>>> 53db73a (alterando telas e conectando ao banco)
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    // End of variables declaration//GEN-END:variables
}
